# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-15 09:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdMapping',
            fields=[
                ('active', models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active')], default=2)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active')], default=2)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('allowed_ip', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportDetails',
            fields=[
                ('active', models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active')], default=2)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('report_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('std', models.CharField(blank=True, max_length=200, null=True)),
                ('Year', models.CharField(blank=True, max_length=200, null=True)),
                ('Total', models.CharField(blank=True, max_length=200, null=True)),
                ('Sci', models.CharField(blank=True, max_length=200, null=True)),
                ('Math', models.CharField(blank=True, max_length=200, null=True)),
                ('Language', models.CharField(blank=True, max_length=200, null=True)),
                ('Social', models.CharField(blank=True, max_length=200, null=True)),
                ('Grade', models.CharField(blank=True, max_length=200, null=True)),
                ('result_status', models.BooleanField(choices=[(True, 'Pass'), (False, 'Fail')])),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_reportdetails', to='masterdata.IdMapping')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
